image: golang:latest

stages:
  - build
  - test

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

vet:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)

test:
  stage: test
  script:
    - go test -race $(go list ./... | grep -v /vendor/)
